identifySuccess:
  has_layout: false
listSetsSuccess:
  has_layout: false
listMetadataFormatsSuccess:
  has_layout: false
listIdentifiersSuccess:
  has_layout: false
listRecordsSuccess:
  has_layout: false
oaiHarvester:
  has_layout: true

harvesterListSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/textarea:
