identifySuccess:
  has_layout: false 
listSetsSuccess:
  has_layout: false
listMetadataFormatsSuccess:
  has_layout: false
listIdentifiersSuccess:
  has_layout: false
listRecordsSuccess:
  has_layout: false
oaiHarvester:
  has_layout: true
