create:
  is_secure:   on
  credentials: [[ editor, administrator ]]

delete:
  is_secure:   on
  credentials: [[ editor, administrator ]]

edit:
  is_secure:   on
  credentials: [[ editor, administrator, translator ]]

list:
  is_secure:   off

show:
  is_secure:  off

update:
  is_secure:   on
  credentials: [[ editor, administrator, translator ]]

all:
  is_secure:   off
