browseTaxonomySuccess:
  javascripts:
    /sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /sfDrupalPlugin/vendor/drupal/misc/tableheader:
    
editSuccess:
  stylesheets:
    /vendor/yui/autocomplete/assets/skins/sam/autocomplete: { position: first }
  javascripts:
    /sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /sfDrupalPlugin/vendor/drupal/misc/collapse:
    /sfDrupalPlugin/vendor/drupal/misc/form:
    /vendor/yui/connection/connection-min:
    /vendor/yui/datasource/datasource-min:
    /vendor/yui/autocomplete/autocomplete-min:
    autocomplete:
    multiInput:
    multiRow:
  components:
    sidebar: [term, contextMenu]

listSuccess:
  javascripts:
    /sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /sfDrupalPlugin/vendor/drupal/misc/collapse:
    /sfDrupalPlugin/vendor/drupal/misc/form:
    /sfDrupalPlugin/vendor/drupal/misc/tableheader:

listTaxonomySuccess:
  javascripts:
    /sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /sfDrupalPlugin/vendor/drupal/misc/tableheader:

indexSuccess:
  components:
    sidebar: [term, contextMenu]
  javascripts:
    blank: 
