delete:
  is_secure:   on
  credentials: [[ contributor, editor, administrator ]]
deleteActorRelation:
  is_secure:  on
  credentials: [[ contributor, editor, administrator ]]
deleteNote:
  is_secure:  on
  credentials: [[ contributor, editor, administrator ]]
deleteProperty:
  is_secure:  on
  credentials: [[ contributor, editor, administrator ]]
deleteTermRelation:
  is_secure:  on
  credentials: [[ contributor, editor, administrator ]]

edit:
  is_secure:   on
  credentials: [[ contributor, editor, administrator, translator ]]
editDc:
  is_secure:   on
  credentials: [[ contributor, editor, administrator, translator ]]
editIsad:
  is_secure:   on
  credentials: [[ contributor, editor, administrator, translator ]]
editMods:
  is_secure:   on
  credentials: [[ contributor, editor, administrator, translator ]]
editRad:
  is_secure:   on
  credentials: [[ contributor, editor, administrator, translator ]]

list:
  is_secure:   off

# not secure is default
#show:
#  is_secure:  off

all:
  is_secure:   off
