editSuccess:
  javascripts: [collapse]

editISADSuccess:
  javascripts: [collapse]

editMODSSuccess:
  javascripts: [collapse]

editDublinCoreSuccess:
  javascripts: [collapse]

all:
  components:
    sidebar: [informationobject, contextMenu]

listSuccess:
  components:
    sidebar: []
