editSuccess:
  javascripts: [/vendor/drupal/misc/collapse]

editIsadSuccess:
  javascripts: [/vendor/drupal/misc/collapse]

editRadSuccess:
  javascripts: [/vendor/drupal/misc/collapse]

editModsSuccess:
  javascripts: [/vendor/drupal/misc/collapse]

editDcSuccess:
  javascripts: [/vendor/drupal/misc/collapse]

all:
  components:
    sidebar: [informationobject, contextMenu]

listSuccess:
  components:
    sidebar: []
