editDcSuccess:
  javascripts: [/sfDrupalPlugin/vendor/drupal/misc/collapse, /sfDrupalPlugin/vendor/drupal/misc/textarea]

editIsadSuccess:
  javascripts: [/sfDrupalPlugin/vendor/drupal/misc/collapse, /sfDrupalPlugin/vendor/drupal/misc/textarea]

editRadSuccess:
  javascripts: [/sfDrupalPlugin/vendor/drupal/misc/collapse, /sfDrupalPlugin/vendor/drupal/misc/textarea]

editModsSuccess:
  javascripts: [/sfDrupalPlugin/vendor/drupal/misc/collapse]

listSuccess:
  components:
    sidebar: []

all:
  components:
    sidebar: [informationobject, contextMenu]

updateIsadError:
  components:
    sidebar: []
    MainMenu: []

updateRadError:
  components:
    sidebar: []
    MainMenu: []