editPhysicalObjectsSuccess:
  javascripts:
    multiDelete:

listSuccess:
  javascripts:
    /sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /sfDrupalPlugin/vendor/drupal/misc/tableheader:

physicalObjects:
  javascripts:
    /sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /sfDrupalPlugin/vendor/drupal/misc/tableheader:
