editSuccess:
  javascripts: [/vendor/drupal/misc/collapse]

editISADSuccess:
  javascripts: [/vendor/drupal/misc/collapse]

editMODSSuccess:
  javascripts: [/vendor/drupal/misc/collapse]

editDublinCoreSuccess:
  javascripts: [/vendor/drupal/misc/collapse]

all:
  components:
    sidebar: [informationobject, contextMenu]

listSuccess:
  components:
    sidebar: []
