editDcSuccess:
  javascripts: [/sfDrupalPlugin/vendor/drupal/misc/collapse, /sfDrupalPlugin/vendor/drupal/misc/textarea, multiDelete, multiInstanceInput, multiInstanceSelect]

editIsadSuccess:
  javascripts: [/sfDrupalPlugin/vendor/drupal/misc/collapse, /sfDrupalPlugin/vendor/drupal/misc/textarea, multiDelete, multiInstanceInput, multiInstanceSelect]

editRadSuccess:
  javascripts: [/sfDrupalPlugin/vendor/drupal/misc/collapse, /sfDrupalPlugin/vendor/drupal/misc/textarea, multiDelete, multiInstanceInput, multiInstanceSelect]

editModsSuccess:
  javascripts: [/sfDrupalPlugin/vendor/drupal/misc/collapse, multiDelete, multiInstanceInput, multiInstanceSelect]

listSuccess:
  components:
    sidebar: []

all:
  components:
    sidebar: [informationobject, contextMenu]

updateIsadError:
  components:
    sidebar: []
    MainMenu: []

updateRadError:
  components:
    sidebar: []
    MainMenu: []