<?php echo '<?xml version="1.0" encoding="'.sfConfig::get('sf_charset', 'UTF-8')."\" ?>\n" ?>

<!-- <?php echo __('Generated by %1% %2%', array('%1%' => $sf_context->getConfiguration()->getApplication(), '%2%' => qubitConfiguration::VERSION)) ?> -->

<oai_dc:dc
  xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/"
  xmlns:dc="http://purl.org/dc/elements/1.1/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc.xsd">

<?php echo get_component('informationobject', 'dublinCoreElements') ?>

</oai_dc:dc>
