delete:
  credentials: administrator
  is_secure: true

deleteTermRelation:
  credentials: [[ contributor, editor, administrator ]]
  is_secure: true

edit:
  credentials: [[ contributor, editor, administrator, translator ]]
  is_secure: true

editIsdiah:
  credentials: [[ contributor, editor, administrator, translator ]]
  is_secure: true
