delete:
  is_secure:   on
  credentials: [[ administrator ]]

deleteTermRelation:
  is_secure:  on
  credentials: [[ contributor, editor, administrator ]]

edit:
  is_secure:   on
  credentials: [[ contributor, editor, administrator, translator ]]

editIsdiah:
  is_secure:   on
  credentials: [[ contributor, editor, administrator, translator ]]

list:
  is_secure:   off

show:
  is_secure:  off

all:
  is_secure:   off
