editIsdiahSuccess:
  javascripts: [/sfDrupalPlugin/vendor/drupal/misc/collapse, /sfDrupalPlugin/vendor/drupal/misc/textarea]

listSuccess:
  components:
    sidebar: []

all:
  components:
    sidebar: [repository, contextMenu]
