editSuccess:
  javascripts: [/vendor/drupal/misc/collapse]

editIsdiahSuccess:
  javascripts: [/vendor/drupal/misc/collapse]

listSuccess:
  components:
    sidebar: []

all:
  components:
    sidebar: [repository, contextMenu]
