deleteSuccess:
  components:
    sidebar: []
    BrowseBox: []
    MainMenu: []
    SearchBox: []

editIsdiahSuccess:
  javascripts: [/sfDrupalPlugin/vendor/drupal/misc/collapse, /sfDrupalPlugin/vendor/drupal/misc/textarea, multiDelete, multiInstanceSelect, multiInstanceInput]

listSuccess:
  javascripts:
  components:
    sidebar: []

autocompleteSuccess:
  javascripts: [-*]
  stylesheets: [-*] 
  components:
    sidebar: []

all:
  components:
    sidebar: [repository, contextMenu]
