prod:
  logger:
    class:   sfNoLogger
    param:
      level:   err
      loggers: ~

cli:
  controller:
    class: sfConsoleController

  request:
    class: sfConsoleRequest

  response:
    class: sfConsoleResponse

test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

all:
#  controller:
#    class: sfFrontWebController
#
#  request:
#    class: sfWebRequest
#
#  response:
#    class: sfWebResponse
#
#  user:
#    class: myUser
#
#  storage:
#    class: sfSessionStorage
#    param:
#      session_name: symfony
#
#  view_cache:
#    class: sfFileCache
#    param:
#      automaticCleaningFactor: 0
#      cacheDir:                %SF_TEMPLATE_CACHE_DIR%
#      lifetime:                86400
#
  i18n:
    class: sfTranslateI18N
    param:
      cache:
        class: sfFileCache
        param:
          automaticCleaningFactor: 0
          cacheDir:                %SF_I18N_CACHE_DIR%
          lifetime:                86400
#
#  routing:
#    class: sfPatternRouting
