rendering: ~

#csrf:
#  class: sfCSRFFilter
#  param:
#    secret: my$ecret # change to something unique

web_debug: ~
security:  ~

history:
  class: sfHistoryPluginFilter

# generally, you will want to insert your own filters here

cache:     ~
common:    ~
execution: ~