transaction:
  class: QubitTransactionFilter

history:
  class: sfHistoryPluginFilter

rendering: ~
security:  ~

# insert your own filters here
siteSettingsFilter:
  class: siteSettingsFilter

cache:     ~
common:    ~
execution: ~
