homepage:
  url:   /
  param: { module: staticpage, action: static, permalink: homepage }

permalink:
  url:   /page/:permalink
  param: { module: staticpage, action: static }

default_index:
  url:   /:module
  param: { action: index }

createDc:
  url: /:module/create/dc
  param: { action: editDc }

editDc:
  url: /:module/edit/dc/:id
  param: { action: editDc }

showDc:
  url: /:module/show/dc/:id
  param: { action: showDc }

createIsaar:
  url: /:module/create/isaar
  param: { action: editIsaar }

editIsaar:
  url: /:module/edit/isaar/:id
  param: { action: editIsaar }

showIsaar:
  url: /:module/show/isaar/:id
  param: { action: showIsaar }

createIsad:
  url: /:module/create/isad
  param: { action: editIsad }

editIsad:
  url: /:module/edit/isad/:id
  param: { action: editIsad }

showIsad:
  url: /:module/show/isad/:id
  param: { action: showIsad }

createIsdiah:
  url: /:module/create/isdiah
  param: { action: editIsdiah }

editIsdiah:
  url: /:module/edit/isdiah/:id
  param: { action: editIsdiah }

showIsdiah:
  url: /:module/show/isdiah/:id
  param: { action: showIsdiah }

createMods:
  url: /:module/create/mods
  param: { action: editMods }

editMods:
  url: /:module/edit/mods/:id
  param: { action: editMods }

showMods:
  url: /:module/show/mods/:id
  param: { action: showMods }

createRad:
  url: /:module/create/rad
  param: { action: editRad }

editRad:
  url: /:module/edit/rad/:id
  param: { action: editRad }

showRad:
  url: /:module/show/rad/:id
  param: { action: showRad }

actorCreate:
  url: /actor/create/:actor_template
  param: { module: actor, action: create }

actorEdit:
  url: /actor/edit/:actor_template/:id
  param: { module: actor, action: edit }

actorShow:
  url: /actor/show/:actor_template/:id
  param: { module: actor, action: show }

informationObjectCreate:
  url: /informationobject/create/:informationobject_template
  param: { module: informationobject, action: create }

informationObjectEdit:
  url: /informationobject/edit/:informationobject_template/:id
  param: { module: informationobject, action: edit }

informationObjectShow:
  url: /informationobject/show/:informationobject_template/:id
  param: { module: informationobject, action: show }

repositoryCreate:
  url: /repository/create/:repository_template
  param: { module: repository, action: create }

repositoryEdit:
  url: /repository/edit/:repository_template/:id
  param: { module: repository, action: edit }

repositoryShow:
  url: /repository/show/:repository_template/:id
  param: { module: repository, action: show }

oai_harvester_harvest_all_sets:
  url: /oai/harvest/:type/:harvestId/*
  param: { module: oai, action: harvesterHarvest }
  requirements:
    harvestId: \d+

oai_harvester_delete:
  url: /oai/deleteRepository/:repositoryId/*
  param: { module: oai, action: harvesterDelete }
  requirements:
    repositoryId: \d+


default:
  url:   /:module/:action/*
