# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

homepage:
  url:   /
  param:
    module: staticpage
    action: static
    permalink: homepage

indexDc:
  url: /:id;dc
  class: QubitRoute
  param:
    module: sfDcPlugin
    action: index
    informationobject_template: dc

createDc:
  url: /;create/dc
  param:
    module: sfDcPlugin
    action: edit
    informationobject_template: dc

duplicateDc:
  url: /;duplicate/dc
  param:
    module: sfDcPlugin
    action: edit
    informationobject_template: dc

editDc:
  url: /:id;edit/dc
  class: QubitRoute
  param:
    module: sfDcPlugin
    action: edit
    informationobject_template: dc

indexEad:
  url: /:id;ead
  class: QubitRoute
  param:
    module: sfEadPlugin
    action: index
    informationobject_template: ead

indexIsaar:
  url: /:id;isaar
  class: QubitRoute
  param:
    module: actor
    action: indexIsaar
    actor_template: isaar

createIsaar:
  url: /;create/isaar
  param:
    module: actor
    action: editIsaar
    actor_template: isaar

editIsaar:
  url: /:id;edit/isaar
  class: QubitRoute
  param:
    module: actor
    action: editIsaar
    actor_template: isaar

indexIsad:
  url: /:id;isad
  class: QubitRoute
  param:
    module: sfIsadPlugin
    action: index
    informationobject_template: isad

createIsad:
  url: /;create/isad
  param:
    module: sfIsadPlugin
    action: edit
    informationobject_template: isad

duplicateIsad:
  url: /;duplicate/isad
  param:
    module: sfIsadPlugin
    action: edit
    informationobject_template: isad

editIsad:
  url: /:id;edit/isad
  class: QubitRoute
  param:
    module: sfIsadPlugin
    action: edit
    informationobject_template: isad

indexIsdf:
  url: /:id;isdf
  class: QubitRoute
  param:
    module: function
    action: index

indexIsdiah:
  url: /:id;isdiah
  class: QubitRoute
  param:
    module: repository
    action: indexIsdiah
    repository_template: isdiah

createIsdiah:
  url: /;create/isdiah
  param:
    module: repository
    action: editIsdiah
    repository_template: isdiah

editIsdiah:
  url: /:id;edit/isdiah
  class: QubitRoute
  param:
    module: repository
    action: editIsdiah
    repository_template: isdiah

indexMods:
  url: /:id;mods
  class: QubitRoute
  param:
    module: sfModsPlugin
    action: index
    informationobject_template: mods

createMods:
  url: /;create/mods
  param:
    module: sfModsPlugin
    action: edit
    informationobject_template: mods

duplicateMods:
  url: /;duplicate/mods
  param:
    module: sfModsPlugin
    action: edit
    informationobject_template: mods

editMods:
  url: /:id;edit/mods
  class: QubitRoute
  param:
    module: sfModsPlugin
    action: edit
    informationobject_template: mods

indexRad:
  url: /:id;rad
  class: QubitRoute
  param:
    module: sfRadPlugin
    action: index
    informationobject_template: rad

createRad:
  url: /;create/rad
  param:
    module: sfRadPlugin
    action: edit
    informationobject_template: rad

duplicateRad:
  url: /;duplicate/rad
  param:
    module: sfRadPlugin
    action: edit
    informationobject_template: rad

editRad:
  url: /:id;edit/rad
  class: QubitRoute
  param:
    module: sfRadPlugin
    action: edit
    informationobject_template: rad

actorCreate:
  url: /;create/:actor_template
  param:
    module: actor
    action: create

actorEdit:
  url: /:id;edit/:actor_template
  class: QubitRoute
  param:
    module: actor
    action: edit

repositoryCreate:
  url: /;create/:repository_template
  param:
    module: repository
    action: create

repositoryEdit:
  url: /:id;edit/:repository_template
  class: QubitRoute
  param:
    module: repository
    action: edit

oai_harvester_harvest_all_sets:
  url: /;oai/harvest/:type/:harvestId/*
  param:
    module: oai
    action: harvesterHarvest
    harvestId: { pattern: \d+ }

oai_harvester_delete:
  url: /;oai/deleteRepository/:repositoryId/*
  param:
    module: oai
    action: harvesterDelete
    repositoryId: { pattern: \d+ }

oai_requests:
  url: /;oai/request
  param:
    module: oai
    action: oai

informationObjectIndex:
  url: /:id;:informationobject_template
  class: QubitRoute
  param:
    module: informationobject
    action: index
    informationobject_template: { pattern: 'dc|ead|isad|mods|rad' }

informationObject/create:
  url: /;create/:informationobject_template
  param:
    module: informationobject
    action: create

informationObject/duplicate:
  url: /;duplicate/:informationobject_template
  param:
    module: informationobject
    action: duplicate

informationObjectEdit:
  url: /:id;edit/:informationobject_template
  class: QubitRoute
  param:
    module: informationobject
    action: edit

informationObjectList:
  url: /;informationobject/list
  class: QubitRoute
  param:
    module: informationobject
    action: list
    id: <?php echo QubitInformationObject::ROOT_ID."\n" ?>

id;default_index:
  url:   /:id;:module
  class: QubitRoute
  param:
    action: index

# QubitRoute only unsets $params[0]
default_index:
  url:   /;:module
  class: QubitRoute
  param:
    action: index

# After default_index to avoid matching /;foo
permalink:
  url: /:permalink
  param:
    module: staticpage
    action: static

id;default:
  url: /:id;:module/:action
  class: QubitRoute
  param:
    id: { pattern: '[^;]+' }

# After id;default to avoid matching array($object, 'module' => 'foo', 'action', => 'edit')
edit:
  url: /;:module/create
  param:
    action: edit

# After edit to avoid matching /;foo/create
create:
  url: /;:module/create
  param:
    action: create

# QubitRoute only unsets $params[0]
default:
  url:   /;:module/:action/*
  class: QubitRoute
