homepage:
  url:   /
  param: { module: staticpage, action: static, permalink: homepage }

login:
  url:   /login
  param: { module: user, action: login }

search:
  url:   /search
  param: { module: search, action: keyword }

browse:
  url:   /browse
  param: { module: term, action: browse }
  
repository:
  url:   /repository
  param: { module: repository, action: list }
  
informationobject:
  url:   /informationobject
  param: { module: informationobject, action: list }
  
actor:
  url:   /actor
  param: { module: actor, action: list }

digitalObject:
  url:   /digitalObject
  param: { module: digitalObject, action: list }

default_module:
  url:   /:permalink
  param: { module: staticpage, action: static }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
