default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:
    /sfDrupalPlugin/vendor/drupal/modules/system/defaults: { media: all }
    /sfDrupalPlugin/vendor/drupal/modules/system/system: { media: all }
    /sfDrupalPlugin/vendor/drupal/themes/garland/style: { media: all }
    /sfDrupalPlugin/vendor/drupal/themes/garland/minnelli/minnelli: { media: all }
    /sfDrupalPlugin/vendor/drupal/themes/garland/print: { media: print }
    /vendor/yui/button/assets/skins/sam/button: {}
    /vendor/yui/menu/assets/skins/sam/menu: {}
    form: {}
    graphic: {}
    layout: {}
    main: { position: last }
    menu: {}

  javascripts:    [/vendor/jquery/jquery, /sfDrupalPlugin/vendor/drupal/misc/drupal, /vendor/yui/yahoo-dom-event/yahoo-dom-event, /vendor/yui/element/element-beta-min, /vendor/yui/button/button-min, /vendor/yui/container/container_core-min, /vendor/yui/menu/menu-min]

  has_layout:     on
  layout:         layout

  components:
    bottomBanner: [sfTranslatePlugin, translate]
    header:       []
    sidebar:      []
    MainMenu:     [menu, mainMenu]
    SearchSidebar: [search, sidebar]
    BrowseSidebar: [browse, sidebar]
    ChangeLanguage: [i18n, changeLanguageList]
