default:
  http_metas:
    content-type: text/html

  metas:
    title:        ICA-AtoM - open source archival description software
    #description:  ICA-AtoM
    #keywords:     ICA-AtoM
    #language:     en
    robots:       index, follow

  stylesheets:    [yui/button/assets/skins/qubit/button-skin, yui/menu/assets/skins/qubit/menu-skin, form, graphic, layout, menu]

  javascripts:    [jquery, drupal, yui/yahoo-dom-event/yahoo-dom-event, yui/element/element-beta-min, yui/button/button-min, yui/container/container_core-min, yui/menu/menu-min]

  has_layout:     on
  layout:         layout

  components:
    bottomBanner: [sfTranslatePlugin, translate]
    header:       []
    sidebar:      []
    MainMenu:     [menu, mainMenu]
    SearchSidebar: [search, Sidebar]
    BrowseSidebar: [browse, Sidebar]
    ChangeLanguageList: [i18n, changeLanguageList]
    ChangeLanguageSelectbox: [i18n, changeLanguageSelectbox]
