default:
  http_metas:
    content-type: text/html

  metas:
    title:        ICA-AtoM - open source archival description software
    #description:  ICA-AtoM
    #keywords:     ICA-AtoM
    #language:     en
    robots:       index, follow

  stylesheets:
    /vendor/drupal/modules/system/defaults: { media: all }
    /vendor/drupal/modules/system/system: { media: all }
    /vendor/drupal/themes/garland/style: { media: all }
    /vendor/drupal/themes/garland/minnelli/minnelli: { media: all }
    /vendor/drupal/themes/garland/print: { media: print }
    /vendor/yui/button/assets/skins/sam/button: {}
    /vendor/yui/menu/assets/skins/sam/menu: {}
    form: {}
    graphic: {}
    layout: {}
    main: { position: last }
    menu: {}

  javascripts:    [jquery, /vendor/drupal/misc/drupal, /vendor/yui/yahoo-dom-event/yahoo-dom-event, /vendor/yui/element/element-beta-min, /vendor/yui/button/button-min, /vendor/yui/container/container_core-min, /vendor/yui/menu/menu-min]

  has_layout:     on
  layout:         layout

  components:
    bottomBanner: [sfTranslatePlugin, translate]
    header:       []
    sidebar:      []
    MainMenu:     [menu, mainMenu]
    SearchSidebar: [search, sidebar]
    BrowseSidebar: [browse, sidebar]
    ChangeLanguageList: [i18n, changeLanguageList]
    ChangeLanguageSelectbox: [i18n, changeLanguageSelectbox]
