default:
  http_metas:
    content-type: text/html; charset=UTF-8

  metas:
    title:        ICA-AtoM -- open source archival description software
    robots:       index, follow
    description:  ICA-AtoM -- open source archival description software
    keywords:     ICA-AtoM open source archival description software
    language:     en

  stylesheets:    [form, graphic, layout, menu]

  javascripts:    []

  has_layout:     on
  layout:         layout

  components:
    footer:       [sfTranslatePlugin, translate]
    header:       []
    sidebar:      []
    MainMenu:                     [menu, mainMenu]
    SearchSidebar:                [search, Sidebar]
    BrowseSidebar:                [browse, Sidebar]
    ChangeLanguageList:           [i18n, changeLanguageList]
