create:
  is_secure:   on
  credentials: [[ contributor, editor, administrator ]]

delete:
  is_secure:   on
  credentials: [[ contributor, editor, administrator ]]

deleteInformationObjectRelationship:
  is_secure:  on
  credentials: [[ contributor, editor, administrator ]]

deleteTermRelationship:
  is_secure:  on
  credentials: [[ contributor, editor, administrator ]]

edit:
  is_secure:   on
  credentials: [[ contributor, editor, administrator ]]

list:
  is_secure:   off

show:
  is_secure:  off

update:
  is_secure:   on
  credentials: [[ contributor, editor, administrator ]]

all:
  is_secure:   off
