delete:
  is_secure:   on
  credentials: [[ contributor, editor, administrator ]]

deleteInformationObjectRelation:
  is_secure:  on
  credentials: [[ contributor, editor, administrator ]]

deleteTermRelation:
  is_secure:  on
  credentials: [[ contributor, editor, administrator ]]

edit:
  is_secure:   on
  credentials: [[ contributor, editor, administrator, translator ]]

editIsaar:
  is_secure:   on
  credentials: [[ contributor, editor, administrator, translator ]]

list:
  is_secure:   off

showIsaar:
  is_secure:  off

all:
  is_secure:   off
