editIsaarSuccess:
  javascripts: [/vendor/drupal/misc/collapse]

listSuccess:
  components:
    sidebar: []

editContactInformationSuccess:
  components:
    sidebar: []

all:
  components:
    sidebar: [actor, contextMenu]
