editISAARSuccess:
  javascripts: [collapse]

listSuccess:
  components:
    sidebar: []

editISIAHContactInformationSuccess:
  components:
    sidebar: []

all:
  components:
    sidebar: [actor, contextMenu]
