propel:
  information_object:
    _attributes: { treeMode: NestedSet }
    id:
    identifier: varchar(255)
    title: varchar(255)
    alternate_title: varchar(255)
    version: varchar(255)
    level_of_description_id: { type: integer, foreignTable: term, foreignReference: id }
    extent_and_medium: longvarchar
    archival_history: longvarchar
    acquisition: longvarchar
    scope_and_content: longvarchar
    appraisal: longvarchar
    accruals: longvarchar
    arrangement: longvarchar
    access_conditions: longvarchar
    reproduction_conditions: longvarchar
    physical_characteristics: longvarchar
    finding_aids: longvarchar
    location_of_originals: longvarchar
    location_of_copies: longvarchar
    related_units_of_description: longvarchar
    rules: longvarchar
    collection_type_id: { type: integer, foreignTable: term, foreignReference: id }
    repository_id:
    tree_id: integer
    tree_left_id: { type: integer, nestedSetLeftKey: true }
    tree_right_id: { type: integer, nestedSetRightKey: true }
    tree_parent_id: integer
    created_at:
    updated_at:

  information_object_term_relationship:
    id:
    information_object_id:
    term_id:
    relationship_type_id: { type: integer, foreignTable: term, foreignReference: id }
    relationship_note: longvarchar
    relationship_start_date: bu_date
    relationship_end_date: bu_date
    date_display: varchar(255)
    created_at:
    updated_at:

  information_object_recursive_relationship:
    id:
    information_object_id:
    related_information_object_id: { type: integer, foreignTable: information_object, foreignReference: id }
    relationship_type_id: { type: integer, foreignTable: term, foreignReference: id }
    relationship_description: longvarchar
    relationship_start_date: bu_date
    relationship_end_date: bu_date
    date_display: varchar(255)
    created_at:
    updated_at:

  note:
    id:
    information_object_id:
    actor_id:
    repository_id:
    function_description_id:
    note: longvarchar
    note_type_id: { type: integer, foreignTable: term, foreignReference: id }
    user_id:
    created_at:
    updated_at:

  digital_object:
    id:
    information_object_id:
    useage_id: { type: integer, foreignTable: term, foreignReference: id }
    name: varchar(255)
    description: longvarchar
    mime_type_id: { type: integer, foreignTable: term, foreignReference: id }
    media_type_id: { type: integer, foreignTable: term, foreignReference: id }
    sequence: integer
    byte_size: integer
    checksum: varchar(100)
    checksum_type_id: { type: integer, foreignTable: term, foreignReference: id }
    location_id: { type: integer, foreignTable: term, foreignReference: id }
    tree_id: integer
    tree_left_id: integer
    tree_right_id: integer
    tree_parent_id: integer
    created_at:
    updated_at:

  digital_object_metadata:
    id:
    digital_object_id:
    element: varchar(255)
    value: longvarchar
    created_at:
    updated_at:

  digital_object_recursive_relationship:
    id:
    digital_object_id:
    related_digital_object_id: { type: integer, foreignTable: digital_object, foreignReference: id }
    relationship_type_id: { type: integer, foreignTable: term, foreignReference: id }
    relationship_description: longvarchar
    created_at:
    updated_at:

  physical_object:
    id:
    name: varchar(255)
    description: longvarchar
    information_object_id:
    location_id: { type: integer, foreignTable: term, foreignReference: id }
    tree_id: integer
    tree_left_id: integer
    tree_right_id: integer
    tree_parent_id: integer
    created_at:
    updated_at:

  actor:
    id:
    authorized_form_of_name: { type: varchar(255), required: true }
    type_of_entity_id: { type: integer, foreignTable: term, foreignReference: id }
    identifiers: varchar(255)
    history: longvarchar
    legal_status: longvarchar
    functions: longvarchar
    mandates: longvarchar
    internal_structures: longvarchar
    general_context: longvarchar
    authority_record_identifier: varchar(255)
    institution_identifier: varchar(255)
    rules: longvarchar
    status_id: { type: integer, foreignTable: term, foreignReference: id }
    level_of_detail_id: { type: integer, foreignTable: term, foreignReference: id }
    sources: longvarchar
    tree_id: integer
    tree_left_id: integer
    tree_right_id: integer
    tree_parent_id: integer
    created_at:
    updated_at:

  actor_name:
    id:
    actor_id:
    name: varchar(255)
    name_type_id: { type: integer, foreignTable: term, foreignReference: id }
    name_note: varchar(255)
    created_at:
    updated_at:

  actor_recursive_relationship:
    id:
    actor_id:
    related_actor_id: { type: integer, foreignTable: actor, foreignReference: id }
    relationship_type_id: { type: integer, foreignTable: term, foreignReference: id }
    relationship_description: longvarchar
    relationship_start_date: bu_date
    relationship_end_date: bu_date
    date_display: varchar(255)
    created_at:
    updated_at:

  actor_term_relationship:
    id:
    actor_id:
    term_id:
    relationship_type_id: { type: integer, foreignTable: term, foreignReference: id }
    relationship_note: longvarchar
    relationship_start_date: bu_date
    relationship_end_date: bu_date
    date_display: varchar(255)
    created_at:
    updated_at:

  contact_information:
    id:
    actor_id:
    contact_type: varchar(255)
    primary_contact: boolean
    street_address: longvarchar
    city: varchar(255)
    region: varchar(255)
    postal_code: varchar(20)
    country_id: { type: integer, foreignTable: term, foreignReference: id }
    longtitude: float
    latitude: float
    telephone: varchar(255)
    fax: varchar(255)
    website: varchar(255)
    email: varchar(255)
    note: longvarchar
    created_at:
    updated_at:

  place:
    id:
    term_id:
    address: longvarchar
    country_id: { type: integer, foreignTable: term, foreignReference: id }
    place_type_id: { type: integer, foreignTable: term, foreignReference: id }
    longtitude: float
    latitude: float
    altitude: float
    created_at:
    updated_at:

  map:
    id:
    title: varchar(255)
    description: longvarchar
    created_at:
    updated_at:

  place_map_relationship:
    id:
    place_id:
    map_id:
    map_icon_image_id: { type: integer, foreignTable: digital_object, foreignReference: id }
    map_icon_description: longvarchar
    relationship_type_id: { type: integer, foreignTable: term, foreignReference: id }
    relationship_note: longvarchar
    created_at:
    updated_at:

  repository:
    id:
    actor_id:
    identifier: varchar(255)
    repository_type_id: { type: integer, foreignTable: term, foreignReference: id }
    officers_in_charge: longvarchar
    geocultural_context: longvarchar
    collecting_policies: longvarchar
    buildings: longvarchar
    holdings: longvarchar
    finding_aids: longvarchar
    opening_times: longvarchar
    access_conditions: longvarchar
    disabled_access: longvarchar
    transport: longvarchar
    research_services: longvarchar
    reproduction_services: longvarchar
    public_facilities: longvarchar
    description_identifier: varchar(255)
    institution_identifier: varchar(255)
    rules: longvarchar
    status_id: { type: integer, foreignTable: term, foreignReference: id }
    level_of_detail_id: { type: integer, foreignTable: term, foreignReference: id }
    sources: longvarchar
    created_at:
    updated_at:

  repository_term_relationship:
    id:
    repository_id:
    term_id:
    relationship_type_id: { type: integer, foreignTable: term, foreignReference: id }
    relationship_note: longvarchar
    created_at:
    updated_at:

  term:
    id:
    taxonomy_id:
    term_name: varchar(255)
    scope_note: longvarchar
    code_alpha: varchar(5)
    code_alpha2: varchar(5)
    code_numeric: integer
    sort_order: integer
    source: varchar(255)
    locked: boolean
    tree_id: integer
    tree_left_id: integer
    tree_right_id: integer
    tree_parent_id: integer
    created_at:
    updated_at:

  taxonomy:
    id:
    name: varchar(50)
    term_use: varchar(5)
    note: longvarchar
    created_at:
    updated_at:

  term_recursive_relationship:
    id:
    term_id:
    related_term_id: { type: integer, foreignTable: term, foreignReference: id }
    relationship_type_id: { type: integer, foreignTable: term, foreignReference: id }
    relationship_description: varchar(255)
    relationship_start_date: bu_date
    relationship_end_date: bu_date
    date_display: varchar(255)
    created_at:
    updated_at:

  event:
    id:
    name: varchar(255)
    description: longvarchar
    start_date: bu_date
    start_time: time
    end_date: bu_date
    end_time: time
    date_display: varchar(255)
    event_type_id: { type: integer, foreignTable: term, foreignReference: id }
    actor_role_id: { type: integer, foreignTable: term, foreignReference: id }
    information_object_id:
    actor_id:
    created_at:
    updated_at:

  event_term_relationship:
    id:
    event_id:
    term_id:
    relationship_type_id: { type: integer, foreignTable: term, foreignReference: id }
    description: longvarchar
    created_at:
    updated_at:

  system_event:
    id:
    system_event_type_id: { type: integer, foreignTable: term, foreignReference: id }
    object_class: varchar(255)
    object_id: integer
    pre_event_snapshot: longvarchar
    post_event_snapshot: longvarchar
    date: timestamp
    user_name: varchar(255)
    user_id:
    created_at:
    updated_at:

  historical_event:
    id:
    term_id:
    historical_event_type_id: { type: integer, foreignTable: term, foreignReference: id }
    start_date: bu_date
    start_time: time
    end_date: bu_date
    end_time: time
    date_display: varchar(255)
    created_at:
    updated_at:

  function_description:
    id:
    term_id:
    function_description_type_id: { type: integer, foreignTable: term, foreignReference: id }
    classification: longvarchar
    domain: longvarchar
    dates: longvarchar
    history: longvarchar
    legislation: longvarchar
    general_context: longvarchar
    description_identifier: varchar(255)
    institution_identifier: varchar(255)
    rules: longvarchar
    status_id: { type: integer, foreignTable: term, foreignReference: id }
    level_id: { type: integer, foreignTable: term, foreignReference: id }
    sources: longvarchar
    created_at:
    updated_at:

  right:
    id:
    information_object_id:
    digital_object_id:
    physical_object_id:
    permission_id: { type: integer, foreignTable: term, foreignReference: id }
    description: longvarchar
    created_at:
    updated_at:

  right_term_relationship:
    id:
    right_id:
    term_id:
    relationship_type_id: { type: integer, foreignTable: term, foreignReference: id }
    description: longvarchar
    created_at:
    updated_at:

  right_actor_relationship:
    id:
    right_id:
    actor_id:
    relationship_type_id: { type: integer, foreignTable: term, foreignReference: id }
    description: longvarchar
    created_at:
    updated_at:

  menu:
    id:
    name: varchar(100)
    url: varchar(255)
    tree_id: integer
    tree_left_id: integer
    tree_right_id: integer
    tree_parent_id: integer
    created_at:
    updated_at:

  static_page:
    id:
    title: varchar(255)
    permalink: { type: varchar(255), unique: true }
    page_content: longvarchar
    stylesheet: varchar(255)
    created_at:
    updated_at:

  user:
    id:
    user_name: varchar(50)
    email: varchar(100)
    sha1_password: varchar(40)
    salt: varchar(32)
    actor_id:
    created_at:
    updated_at:

  user_term_relationship:
    id:
    user_id:
    term_id:
    relationship_type_id: { type: integer, foreignTable: term, foreignReference: id }
    repository_id:
    description: longvarchar
    created_at:
    updated_at:
