delete:
  is_secure:   on
  credentials: [[ contributor, editor, administrator ]]

update:
  is_secure:   on
  credentials: [[ contributor, editor, administrator, translator ]]
  
multiFileUpload:
  is_secure:   on
  credentials: [[ contributor, editor, administrator, translator ]]

all:
  is_secure:   off
