editSuccess:
  javascripts: [/sfDrupalPlugin/vendor/drupal/misc/collapse]

showFullScreenSuccess:
  layout: layout_fullscreen
  components:
    all: []
    bottomBanner: [sfTranslatePlugin, translate]
