create:
  credentials: administrator
  is_secure: true

delete:
  credentials: administrator
  is_secure: true

edit:
  credentials: [[ administrator, translator ]]
  is_secure: true

list:
  credentials: administrator
  is_secure: true

passwordEdit:
  credentials: [[ researcher, contributor, editor, administrator, translator ]]
  is_secure: true

passwordUpdate:
  credentials: [[ researcher, contributor, editor, administrator, translator ]]
  is_secure: true

show:
  credentials: [[ researcher, contributor, editor, administrator, translator ]]
  is_secure: true

update:
  credentials: administrator
  is_secure: true
