create:
  is_secure:   on
  credentials: administrator

delete:
  is_secure:   on
  credentials: administrator

edit:
  is_secure:   on
  credentials: [[ administrator, translator ]]

list:
  is_secure:   on
  credentials: administrator

passwordEdit:
  is_secure:   on
  credentials: [[ researcher, contributor, editor, administrator, translator ]]

passwordUpdate:
  is_secure:   on
  credentials: [[ researcher, contributor, editor, administrator, translator ]]

show:
  is_secure:   on
  credentials: [[ researcher, contributor, editor, administrator, translator ]]

update:
  is_secure:   on
  credentials: administrator

all:
  is_secure:   off
