editSuccess:
  stylesheets:
    /vendor/yui/autocomplete/assets/skins/sam/autocomplete: { position: first }
  javascripts: 
    /sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /sfDrupalPlugin/vendor/drupal/misc/collapse:
    /sfDrupalPlugin/vendor/drupal/misc/form:
    /sfDrupalPlugin/vendor/drupal/misc/textarea:
    /sfDrupalPlugin/vendor/drupal/modules/user/user:
    /vendor/yui/animation/animation-min:
    /vendor/yui/connection/connection-min:
    /vendor/yui/datasource/datasource-min:
    /vendor/yui/autocomplete/autocomplete-min:
    autocomplete:
    select:

editActorAclSuccess:
  stylesheets:
    /vendor/yui/autocomplete/assets/skins/sam/autocomplete: { position: first }
    /vendor/yui/container/assets/skins/sam/container: { position: first }
  javascripts: 
    /sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /sfDrupalPlugin/vendor/drupal/misc/collapse:
    /sfDrupalPlugin/vendor/drupal/misc/form:
    /sfDrupalPlugin/vendor/drupal/misc/textarea:
    /sfDrupalPlugin/vendor/drupal/modules/user/user:
    /vendor/yui/animation/animation-min:
    /vendor/yui/connection/connection-min:
    /vendor/yui/datasource/datasource-min:
    /vendor/yui/autocomplete/autocomplete-min:
    /vendor/yui/container/container-min:
    autocomplete:
    select:
    multiDelete:

editInformationObjectAclSuccess:
  stylesheets:
    /vendor/yui/autocomplete/assets/skins/sam/autocomplete: { position: first }
    /vendor/yui/container/assets/skins/sam/container: { position: first }
  javascripts: 
    /sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /sfDrupalPlugin/vendor/drupal/misc/collapse:
    /sfDrupalPlugin/vendor/drupal/misc/form:
    /sfDrupalPlugin/vendor/drupal/misc/textarea:
    /sfDrupalPlugin/vendor/drupal/modules/user/user:
    /vendor/yui/animation/animation-min:
    /vendor/yui/connection/connection-min:
    /vendor/yui/datasource/datasource-min:
    /vendor/yui/autocomplete/autocomplete-min:
    /vendor/yui/container/container-min:
    autocomplete:
    select:
    aclDialog:

editTermAclSuccess:
  stylesheets:
    /vendor/yui/autocomplete/assets/skins/sam/autocomplete: { position: first }
    /vendor/yui/container/assets/skins/sam/container: { position: first }
  javascripts: 
    /sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /sfDrupalPlugin/vendor/drupal/misc/collapse:
    /sfDrupalPlugin/vendor/drupal/misc/form:
    /sfDrupalPlugin/vendor/drupal/misc/textarea:
    /sfDrupalPlugin/vendor/drupal/modules/user/user:
    /vendor/yui/animation/animation-min:
    /vendor/yui/connection/connection-min:
    /vendor/yui/datasource/datasource-min:
    /vendor/yui/autocomplete/autocomplete-min:
    /vendor/yui/container/container-min:
    autocomplete:
    select:
    aclDialog:

listSuccess:
  javascripts:
    /sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /sfDrupalPlugin/vendor/drupal/misc/tableheader:

indexActorAclSuccess:
  javascripts:
    /sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /sfDrupalPlugin/vendor/drupal/misc/tableheader:
 
indexTermAclSuccess:
  javascripts:
    /sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /sfDrupalPlugin/vendor/drupal/misc/tableheader:

indexInformationObjectAclSuccess:
  javascripts:
    /sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /sfDrupalPlugin/vendor/drupal/misc/tableheader:

passwordEditSuccess:
  javascripts:
    /sfDrupalPlugin/vendor/drupal/modules/user/user:
