editSuccess:
  stylesheets:
    /vendor/yui/autocomplete/assets/skins/sam/autocomplete: { position: first }
  javascripts: 
    - /vendor/yui/connection/connection-min
    - /vendor/yui/datasource/datasource-min
    - /vendor/yui/autocomplete/autocomplete-min
    - autocomplete
    - multiDelete
    - /sfDrupalPlugin/vendor/drupal/misc/collapse
    - /sfDrupalPlugin/vendor/drupal/misc/textarea
    - /sfDrupalPlugin/vendor/drupal/modules/user/user

passwordEditSuccess:
  javascripts: [ /sfDrupalPlugin/vendor/drupal/modules/user/user ]
