list:
  is_secure:   on
  credentials: [[ administrator, translator ]]

edit:
  is_secure:   on
  credentials: [[ administrator, translator ]]

create:
  is_secure:   on
  credentials: administrator

delete:
  is_secure:   on
  credentials: administrator

update:
  is_secure:   on
  credentials: [[ administrator, translator ]]

all:
  is_secure:   off
