list:
  is_secure:   on
  credentials: administrator

edit:
  is_secure:   on
  credentials: administrator

create:
  is_secure:   on
  credentials: administrator

delete:
  is_secure:   on
  credentials: administrator

update:
  is_secure:   on
  credentials: administrator

all:
  is_secure:   off
