list:
  credentials: [[ administrator, translator ]]
  is_secure: true

edit:
  credentials: [[ administrator, translator ]]
  is_secure: true

create:
  credentials: administrator
  is_secure: true

delete:
  credentials: administrator
  is_secure: true

update:
  credentials: [[ administrator, translator ]]
  is_secure: true
