create:
  credentials: [[ contributor, editor, administrator ]]
  is_secure: true

createPlaceMapRelation:
  credentials: [[ contributor, editor, administrator ]]
  is_secure: true

delete:
  credentials: [[ contributor, editor, administrator ]]
  is_secure: true

deletePlaceMapRelation:
  credentials: [[ contributor, editor, administrator ]]
  is_secure: true

edit:
  credentials: [[ contributor, editor, administrator ]]
  is_secure: true

editPlaceMapRelation:
  credentials: [[ contributor, editor, administrator ]]
  is_secure: true

list:
  credentials: [[ contributor, editor, administrator ]]
  is_secure: true

update:
  credentials: [[ contributor, editor, administrator ]]
  is_secure: true

updatePlaceMapRelation:
  credentials: [[ contributor, editor, administrator ]]
  is_secure: true
